name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Which tag to release
        options: 
        - v0.1.5

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    name: Build Release Assets ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load version
        run: git pull && git checkout ${{ github.event.inputs.version }}  

      - name: Set up docker
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Docker Hub Login 
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ vars.DOCKER_HUB_USERNAME }} --password-stdin 

      - name: Build API 
        run: cd api && docker build --push --tag markdessain/formulosity:${{ github.event.release.tag_name }}-api .

      - name: Build UI
        run: cd ui && docker build --push --tag markdessain/formulosity:${{ github.event.release.tag_name }}-ui .
